FROM golang:1.19-alpine
WORKDIR /app
COPY go.sum go.sum
COPY go.mod go.mod
RUN go mod download
COPY . .
RUN go build -o bin ./cmd/hashvalidate

FROM alpine:3.14
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=0 /app/bin /app/bin
CMD /app/bin
